WITH latest_export AS (
    SELECT MAX(EXPORT_DATE) AS max_export_date
    FROM OBJECT_LAYER.OBJECT_LAYER.OL__LEANDNA_LINE_OF_BALANCE_BY_WEEK
)
SELECT 
    LEFT(PRODUCING_LOCATION, 4) AS PLANT,
    SUM(ON_HAND_UNRESTRICTED) AS SUM_UNRESTRICTED,
    SUM(ON_HAND_BLOCKED) AS SUM_BLOCKED
FROM OBJECT_LAYER.OBJECT_LAYER.OL__LEANDNA_LINE_OF_BALANCE_BY_WEEK lob
JOIN latest_export le ON lob.EXPORT_DATE = le.max_export_date
GROUP BY PLANT;
