SELECT
    P.PLANT,
    P.PLANT_NAME,
    P.POSTAL_CODE,
    P.CITY,
    P.SALES_ORGANIZATION_FOR_INTERCOMPANY_BILLING,
    P.COUNTRY_KEY,
    P.COMPANY_CODE,
    CT.SHORT_DESCRIPTION AS COUNTRY_NAME
FROM XXXXXXXX AS P
LEFT JOIN (
    SELECT 
        COUNTRY_KEY,
        SHORT_DESCRIPTION
    FROM XXXXXXXXXXXX
    WHERE LANGUAGE_KEY = 'E'
) AS CT
    ON P.COUNTRY_KEY = CT.COUNTRY_KEY
WHERE 
    P.PLANT_NAME NOT LIKE 'ZZZ%'
ORDER BY 
    P.PLANT ASC;
