# Stock Volume Analysis #

SELECT 
    LTRIM(MV.MATERIAL_NUMBER, '0') AS MATERIAL_NUM,
    MV.VALUATION_AREA AS PLANT,
    MV.TOTAL_VALUATED_STOCK,
    MV.VALUE_OF_TOTAL_VALUATED_STOCK,
    MV.STANDARD_PRICE / MV.PRICE_UNIT AS PRICE_PER,
    MT.DESCR AS DESCRIPTION,
    MS_SUM.PRODUCT_HIERARCHY,
    MV.LAST_REFRESH_AT
FROM XXXXXXXX AS MV
LEFT JOIN XXXXXXXX AS MT
    ON LTRIM(MV.MATERIAL_NUMBER, '0') = LTRIM(MT.MATERIAL, '0')
    AND MT.LANGUAGE = 'E'
LEFT JOIN (
    SELECT 
        MATERIAL_NUMBER, 
        MAX(PRODUCT_HIERARCHY) AS PRODUCT_HIERARCHY
    FROM X
    GROUP BY MATERIAL_NUMBER
) AS MS_SUM
    ON LTRIM(MV.MATERIAL_NUMBER, '0') = LTRIM(MS_SUM.MATERIAL_NUMBER, '0')
WHERE 
    MV.VALUATION_AREA IN ('XXXX', 'XXXX', 'XXXX', 'XXXX')
    AND MV.TOTAL_VALUATED_STOCK <> 0
