# Etsy Database #

SELECT
    SHIP_STATE,
    SUM(GROSS_AMOUNT),
    SUM(NET_AMOUNT)
FROM ITEMS
JOIN SALES
    ON ITEMS.ORDER_ID = SALES.ORDER_ID
GROUP BY SHIP_STATE
ORDER BY SUM(NET_AMOUNT) DESC

SELECT
  YEAR(ORDER_DATE),
  SUM(GROSS_AMOUNT),
  SUM(FEES),
  SUM(NET_AMOUNT)
FROM
  ETSY.PUBLIC.SALES
GROUP BY YEAR(ORDER_DATE)
ORDER BY YEAR(ORDER_DATE) DESC
